package main

import "database/sql"

type AutoGenerated struct {
	ID        int    `json:"id"`
	UUID      string `json:"uuid"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	Meta      struct {
		OsmID             interface{} `json:"osm_id"`
		GoogleMapsPlaceID string      `json:"google_maps_place_id"`
	} `json:"meta"`
	Type string `json:"type"`
	Name struct {
		En string `json:"en"`
		Ru string `json:"ru"`
		Uk string `json:"uk"`
	} `json:"name"`
	PublicName struct {
		En string `json:"en"`
		Ru string `json:"ru"`
		Uk string `json:"uk"`
	} `json:"public_name"`
	PostCode []string `json:"post_code"`
	Katottg  string   `json:"katottg"`
	Koatuu   string   `json:"koatuu"`
	Lng      float64  `json:"lng"`
	Lat      float64  `json:"lat"`
	ParentID int      `json:"parent_id"`
}

func main() {
	sql, err := sql.Open("postgre", "")
	_, _ = sql, err
}
