version: "3"

services:
  postgres:
    image: "postgres:14.2-alpine"
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    networks:
      - local

volumes:
  postgres_storage:

networks:
  local:
    driver: bridge