DROP TABLE IF EXISTS app_user;

DROP TABLE IF EXISTS category;

DROP TABLE IF EXISTS subscription;

DROP TABLE IF EXISTS locality;

DROP TYPE IF EXISTS locality_type;

DROP TYPE IF EXISTS language;

DROP TABLE IF EXISTS help;

DROP EXTENSION IF EXISTS fuzzystrmatch;

DROP EXTENSION IF EXISTS pgcrypto;
