DROP TABLE IF EXISTS app_user;

DROP TABLE IF EXISTS category;

DROP TABLE IF EXISTS request;

DROP TABLE IF EXISTS locality;

DROP TYPE IF EXISTS locality_type;

DROP TABLE IF EXISTS help;

DROP EXTENSION IF EXISTS fuzzystrmatch;
